Repository Automattic/vip-cli, pull requests merged in 2018-06, with the labels that each got.

#104 Rethink vip app fields
  src/bin/vip-app-list.js
  src/bin/vip-app.js
  src/lib/cli/format.js
Labels: Upstream Dependency, [Status] Ready to Merge

#118 Add Analytics lib
  .gitignore
  .npmignore
  __tests__/lib/analytics/google-analytics.js
  __tests__/lib/analytics/tracks.js
  config/config.local.json
  config/config.publish.json
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  scripts/prepare-config.js
  src/lib/analytics.js
  src/lib/analytics/google-analytics.js
  src/lib/analytics/index.js
  src/lib/analytics/tracks.js
  src/lib/cli/command.js
  src/lib/env.js
Labels: [Status] Needs Review, [Status] Retro Review

#122 Integrate Analytics
  __tests__/lib/analytics/clients/google-analytics.js
  __tests__/lib/analytics/clients/tracks.js
  __tests__/lib/token.js
  config/config.local.json
  config/config.publish.json
  package.json
  src/bin/vip-app-list.js
  src/bin/vip-app.js
  src/bin/vip-sync.js
  src/bin/vip.js
  src/lib/analytics.js
  src/lib/analytics/clients/client.js
  src/lib/analytics/clients/google-analytics.js
  src/lib/analytics/clients/stub.js
  src/lib/analytics/clients/tracks.js
  src/lib/analytics/index.js
  src/lib/cli/command.js
  src/lib/token.js
  src/lib/tracker.js
Labels: [Status] Needs Review

#125 Add debug on secure keychain failure
  src/lib/keychain.js
Labels: [Status] Needs Review

#135 Throw on token set failures.
  src/bin/vip.js
  src/lib/keychain/insecure.js
Labels: [Status] Needs Review

#138 Switch to configstore
  package-lock.json
  package.json
  src/lib/keychain/insecure.js
Labels: [Status] Needs Review

#131 Update args from 3.0.8 to 5.0.0
  package-lock.json
  package.json
  src/lib/cli/command.js
Labels: [Status] Needs Review, [Status] Retro Review
