Repository Automattic/vip-cli, pull requests merged in 2019-04, with the labels that each got.

#297 Fix wp subshell cursor
  src/bin/vip-wp.js
Labels: [Status] Ready to Merge

#281 Make wp shell impossible in sub-shell mode
  src/bin/vip-wp.js
Labels: [Status] Ready to Merge

#295 Remove help and version in favor of -h/--help and -v/--version
  src/lib/cli/command.js
Labels: [Status] Has Feedback

#304 Fix .toLowerCase error on app/env picker
  src/lib/cli/command.js
  src/lib/cli/prompt.js
Labels: [Status] Ready to Merge

#288 Add error message for rate limit
  src/bin/vip-wp.js
Labels: [Status] Ready to Merge

#300 Hook up input pipe for WP CLI
  src/bin/vip-wp.js
Labels: [Status] Ready to Merge

#303 WP CLI - More comprehensive subshell cursor fix
  src/bin/vip-wp.js
Labels: [Status] Needs Review

#306 Set default rows/columns when out stream isn't a TTY
  src/bin/vip-wp.js
Labels: [Status] Ready to Merge

#310 WP CLI: Missing quotes in wp cli commands
  src/bin/vip-wp.js
  src/lib/cli/format.js
Labels: [Status] Needs Review

#308 Add environment aliases support
  __tests__/lib/cli/envAlias.js
  src/lib/cli/command.js
  src/lib/cli/envAlias.js
Labels: [Status] Ready to Merge

#312 Clone process.argv to avoid overwriting it
  src/lib/cli/envAlias.js
Labels: [Status] Needs Review
