Repository Automattic/vip-cli, pull requests merged in 2020-08, with the labels that each got.

#575 Add import files validation
  .gitignore
  __tests__/lib/vip-import-validate-files.js
  src/bin/vip-import-validate-files.js
  src/lib/vip-import-validate-files.js
Labels: [Status] Ready to Merge

#582 Import files: Add multiple nested folders validation
  __tests__/lib/vip-import-validate-files.js
  src/bin/vip-import-validate-files.js
  src/lib/vip-import-validate-files.js
Labels: [Status] Has Feedback

#587 Fix media files validation bug and support multisite validation
  src/bin/vip-import-validate-files.js
  src/lib/vip-import-validate-files.js
Labels: [Status] Needs Review

#589 Add Tracks events for validation commands
  src/bin/vip-import-validate-files.js
  src/bin/vip-import-validate-sql.js
Labels: [Status] Needs Review
