Repository Automattic/vip-cli, pull requests merged in 2021-04, with the labels that each got.

#713 Dev-environment: Fixes path location for template file
  src/lib/dev-environment.js
Labels: [Status] Ready to Merge

#712 FORNO-555: Add start media import command
  src/bin/vip-import-media.js
Labels: [Status] Has Feedback, [Status] Ready to Merge

#717 Dev Env stop
  package.json
  src/bin/vip-dev-environment-stop.js
  src/bin/vip-dev-environment.js
  src/lib/dev-environment.js
Labels: [Status] Needs Review

#716 FORNO-557: Display Media Import Global Errors
  src/lib/media-import/status.js
Labels: [Status] Ready to Merge

#718 Dev-environment adds info
  package.json
  src/bin/vip-dev-environment-info.js
  src/bin/vip-dev-environment.js
  src/lib/dev-environment.js
Labels: [Status] Ready to Merge

#715 FORNO-555: Fix `import media status` sub command
  package.json
  src/bin/vip-import-media.js
  src/bin/vip-import.js
  src/lib/cli/command.js
Labels: [Status] Ready to Merge

#719 FORNO-557: Display and Export File Errors
  src/bin/vip-import-media-status.js
  src/bin/vip-import.js
  src/bin/vip.js
  src/lib/media-import/status.js
Labels: [Status] Ready to Merge

#720 FORNO-557: Fix fs promises module
  src/lib/media-import/status.js
Labels: [Status] Ready to Merge

#721 adds --all swith to the dev-env info
  src/bin/vip-dev-environment-info.js
  src/lib/dev-environment.js
Labels: [Status] Needs Review

#722 fix bug and adds example
  __tests__/lib/dev-environment.js
  src/bin/vip-dev-environment-create.js
  src/lib/dev-environment.js
Labels: [Status] Needs Review

#723 Block SQL Imports for k8s sites
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#725 Multisite sql dump detection
  __tests__/lib/validations/is-multi-site-sql-dump.js
  src/lib/validations/is-multi-site-sql-dump.js
Labels: [Status] Needs Review

#726 Add/dev env wp
  package.json
  src/bin/vip-dev-environment-info.js
  src/bin/vip-dev-environment-start.js
  src/bin/vip-dev-environment-stop.js
  src/bin/vip-dev-environment-wp.js
  src/bin/vip-dev-environment.js
  src/lib/dev-environment.js
Labels: [Status] Needs Review

#729 Adds info to creation
  src/bin/vip-dev-environment-create.js
  src/lib/dev-environment.js
Labels: [Status] Ready to Merge

#730 Dev-environment Support @naming
  __tests__/lib/dev-environment.js
  src/bin/vip-dev-environment-create.js
  src/bin/vip-dev-environment-destroy.js
  src/bin/vip-dev-environment-info.js
  src/bin/vip-dev-environment-start.js
  src/bin/vip-dev-environment-stop.js
  src/bin/vip-dev-environment-wp.js
  src/lib/constants/dev-environment.js
  src/lib/dev-environment.js
Labels: [Status] Needs Review

#732 Refactors dev-env to split responsibilities
  __tests__/lib/dev-environment/dev-environment-cli.js
  __tests__/lib/dev-environment/dev-environment-core.js
  src/bin/vip-dev-environment-create.js
  src/bin/vip-dev-environment-destroy.js
  src/bin/vip-dev-environment-info.js
  src/bin/vip-dev-environment-start.js
  src/bin/vip-dev-environment-stop.js
  src/bin/vip-dev-environment-wp.js
  src/lib/constants/dev-environment.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Has Feedback

#735 FORNO-643: Fix invalid URL error message
  src/bin/vip-import-media.js
  src/bin/vip-import.js
  src/lib/media-import/status.js
Labels: [Status] Ready to Merge

#733 Add/dev env propmts
  __tests__/lib/dev-environment/dev-environment-cli.js
  __tests__/lib/dev-environment/dev-environment-core.js
  src/bin/vip-dev-environment-create.js
  src/lib/constants/dev-environment.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#736 Update/create error
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-environment-create.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Has Feedback

#734 Fetch image tags from Docker Hub in dev environment
  __tests__/lib/dev-environment/dev-environment-cli.js
  __tests__/lib/dev-environment/docker-hub-jetpack-response.json
  __tests__/lib/dev-environment/docker-hub-wp-response.json
  src/lib/constants/dev-environment.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge
