Repository Automattic/vip-cli, pull requests merged in 2021-05, with the labels that each got.

#739 FORNO-659 Add overwriteExisting flag to media-import cmd
  src/bin/vip-import-media.js
  src/bin/vip-import.js
Labels: [Status] Ready to Merge

#737 Fetching base info
  __tests__/lib/dev-environment/dev-environment-core.js
  src/bin/vip-dev-environment-create.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#741 Adds search info line
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#742 Prevent calling isVip when logout command is being executed
  src/bin/vip.js
Labels: [Status] Needs Review

#743 Update socket.io-client package
  package-lock.json
  package.json
Labels: [Status] Needs Review

#709 PIE-2632: fix site-type validation for sql file
  __tests__/lib/validations/is-multi-site-sql-dump.js
  package-lock.json
  package.json
  src/lib/validations/is-multi-site-sql-dump.js
  src/lib/validations/site-type.js
Labels: [Status] Needs Review

#745 Change usage of json2csv according to new version
  src/lib/cli/format.js
Labels: [Status] Needs Review

#747 Update lando to 3.1
  package-lock.json
  package.json
Labels: [Status] Needs Review

#748 Add/dev env add site
  package.json
  src/bin/vip-dev-environment-add-site.js
  src/bin/vip-dev-environment.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#755 refactor exec
  package.json
  src/bin/vip-dev-environment-add-site.js
  src/bin/vip-dev-environment-exec.js
  src/bin/vip-dev-environment.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#761 Dev-Env: Adds ability to do soft destroy
  src/bin/vip-dev-environment-destroy.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Has Feedback

#762 FORNO-691: Add importIntermediateImages flag
  src/bin/vip-import-media.js
Labels: [Status] Ready to Merge

#764 FORNO-680: Update Media Import language
  src/bin/vip-import-media.js
Labels: [Status] Ready to Merge

#763 PIE-2684 Add search-replace recommendation to InnoDB check
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#765 FORNO-665: Public facing Media Import
  package.json
  src/bin/vip-import-media-status.js
  src/bin/vip-import-media.js
  src/bin/vip-import.js
  src/bin/vip.js
  src/lib/cli/command.js
  src/lib/media-import/media-file-import.js
  src/lib/media-import/progress.js
  src/lib/media-import/status.js
Labels: [Status] Needs Review

#770 rename dev-env
  __tests__/lib/dev-environment/dev-environment-cli.js
  package.json
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env.js
  src/bin/vip.js
  src/lib/constants/dev-environment.js
Labels: [Status] Needs Review

#772 dev-environment: Fix typo in intro
  src/lib/constants/dev-environment.js
Labels: [Status] Needs Review
