Repository Automattic/vip-cli, pull requests merged in 2021-01, with the labels that each got.

#588 Drop Node 8 Support, Update Babel, & Support modern syntax across node versions
  .circleci/config.yml
  .flowconfig
  babel.config.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#626 Move vip-import-sql to the CLI command line output
  package.json
  src/bin/vip-import-sql.js
  src/bin/vip-import-validate-files.js
  src/bin/vip-import-validate-sql.js
  src/bin/vip-import.js
Labels: [Status] Needs Review

#622 Add a validation to check each line for ENGINE!=InnoDB
  __fixtures__/validations/bad-sql-dump.sql
  __tests__/lib/validations/sql.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#629 Import SQL: Fix Tracks properties
  src/bin/vip-import-sql.js
  src/lib/search-and-replace.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#625 file import validator: Allow SVG files
  src/lib/vip-import-validate-files.js
Labels: [Status] Needs Review

#631 Tracks: Show an error via debug when a tracks event name or prop is invalid
  src/lib/analytics/clients/tracks.js
Labels: [Status] Needs Review

#633 SQL Search & Replace: Don't specify stream encoding
  src/lib/search-and-replace.js
Labels: [Status] Needs Review

#632 Setup dev release 2 dev1
  .publishrc
  package-lock.json
  package.json
Labels: [Status] Needs Review

#630 Import SQL: Add and clean up progress logs
  __tests__/lib/search-and-replace.js
  package-lock.json
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
  src/lib/cli/format.js
  src/lib/client-file-uploader.js
  src/lib/search-and-replace.js
  src/lib/validations/sql.js
Labels: [Status] Has Feedback

#634 SQL Import: Error out if the file is too large
  __tests__/lib/client-file-uploader.js
  src/bin/vip-import-sql.js
  src/lib/client-file-uploader.js
  src/lib/site-import/db-file-import.js
Labels: [Status] Needs Review

#635 SQL Import: Move some debug output to debug command
  src/bin/vip-import-sql.js
  src/lib/client-file-uploader.js
Labels: [Status] Ready to Merge

#638 Fix standalone Search and Replace command
  src/bin/vip.js
Labels: [Status] Needs Review

#637 SQL Import: Fix help prompts for imports and S-R
  package-lock.json
  src/bin/vip-import-sql.js
  src/bin/vip-import.js
  src/bin/vip-search-replace.js
Labels: [Status] Has Feedback

#642 Fix output for the standalone S-R command
  src/bin/vip-search-replace.js
Labels: [Status] Needs Review

#640 Block import of multisite into single site and vice versa
  src/bin/vip-import-sql.js
  src/lib/cli/exit.js
  src/lib/tracker.js
  src/lib/validations/is-multi-site-sql-dump.js
  src/lib/validations/is-multi-site.js
  src/lib/validations/line-by-line.js
  src/lib/validations/site-type.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#645 Clean up search and replace pairs when importing
  __tests__/lib/search-and-replace.js
  src/lib/search-and-replace.js
Labels: [Status] Needs Review

#647 Bumping @next to v2.0.0-dev3
  package-lock.json
  package.json
Labels: [Status] Needs Review

#648 More robust check for import status object
  src/lib/site-import/status.js
Labels: [Status] Needs Review

#649 App command: include launch status
  src/bin/vip-app.js
Labels: [Status] Needs Review

#646 Fix SQL validation for imports
  src/lib/validations/line-by-line.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#639 SQL Imports: Simplify import update progress logs
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
  src/lib/cli/progress.js
  src/lib/client-file-uploader.js
  src/lib/search-and-replace.js
  src/lib/validations/site-type.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review, [Status] Retro Review

#653 SQL Imports: Reinstitute check for file access in command gate fn
  src/bin/vip-import-sql.js
  src/lib/client-file-uploader.js
Labels: [Status] Needs Review

#654 FORNO-506: Add optional IF NOT EXISTS to CREATE TABLE checks
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#659 Fix import file path reference to work cross-platform
  src/lib/client-file-uploader.js
Labels: 2.0 blocker, [Status] Needs Review

#655 Streamline import progress output
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
  src/lib/cli/format.js
  src/lib/cli/progress.js
  src/lib/client-file-uploader.js
  src/lib/search-and-replace.js
  src/lib/validations/site-type.js
  src/lib/validations/sql.js
Labels: 2.0 blocker, [Status] Needs Review

#657 Add environment launched status to the import sql command
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
Labels: 2.0 blocker, [Status] Has Feedback

#661 SQL Import: Add a gate to check if path is a file
  src/bin/vip-import-sql.js
  src/lib/client-file-uploader.js
Labels: 2.0 blocker, [Status] Needs Review

#662 Bump @automattic/vip-search-replace@1.0.7 and handle exception
  package-lock.json
  package.json
  src/lib/search-and-replace.js
Labels: [Status] Needs Review

#660 SQL Imports: Another iteration on the UX and underlying API
  src/bin/vip-import-sql-status.js
  src/bin/vip-import-sql.js
  src/lib/cli/format.js
  src/lib/cli/progress.js
  src/lib/client-file-uploader.js
  src/lib/search-and-replace.js
  src/lib/site-import/status.js
  src/lib/validations/sql.js
Labels: 2.0 blocker

#663 SQL Import: Include completed ts, show failed on job step, & further clean up output
  src/lib/site-import/status.js
Labels: 2.0 blocker

#656 SQL Import: Update wording around SQL Import
  src/bin/vip-import-sql-status.js
  src/bin/vip-import-sql.js
  src/lib/site-import/status.js
Labels: 2.0 blocker, [Status] In Progress

#658 Fix search replace output for SQL import command
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
  src/lib/cli/format.js
Labels: 2.0 blocker

#664 Append app & env ids to output
  src/lib/cli/command.js
Labels: 2.0 blocker, [Status] Ready to Merge
