Repository Automattic/vip-cli, pull requests merged in 2021-02, with the labels that each got.

#665 SQL Import: UX Enhancements including restoring functionality to show upload percentage & API call optimization
  src/bin/vip-import-sql.js
  src/lib/cli/format.js
  src/lib/cli/progress.js
  src/lib/client-file-uploader.js
  src/lib/site-import/status.js
Labels: 2.0 blocker, [Status] Has Feedback

#666 Add fixtures dir to .npmignore
  .npmignore
Labels: 2.0 blocker

#667 Bumping vip-search-replace to v1.0.8
  package-lock.json
  package.json
Labels: 2.0 blocker

#672 vip-search-replace dep -- bump to 1.0.10
  package-lock.json
  package.json
Labels: 2.0 blocker

#674 Fix: SQL file validation output disappearing
  src/bin/vip-import-sql.js
Labels: 2.0 blocker, [Status] Needs Review

#677 Guard against empty importStatus data
  src/bin/vip-import-sql.js
Labels: 2.0 blocker, [Status] Ready to Merge

#673 2.0.0
  .publishrc
  package-lock.json
  package.json
  src/lib/search-and-replace.js
Labels: 2.0 blocker, [Status] Needs Review

#682 bump search-replace package to v1.0.12
  package-lock.json
  package.json
Labels: [Status] Needs Review

#686 Update development "npm link" message to use debug
  src/bin/vip.js
Labels: [Status] Needs Review

#687 Update vip-search-replace to ^1.0.13
  package-lock.json
  package.json
Labels: [Status] Needs Review

#688 Bump Version to 2.0.2
  README.md
  package-lock.json
  package.json
Labels: [Status] Needs Review

#680 SQL Validation: Add stricter checking for the TRIGGER statement
  src/lib/validations/sql.js
Labels: [Status] Ready to Merge

#690 Adjust renovate to let the team know when PRs need review
  renovate.json
Labels: [Status] Needs Review
