Repository Automattic/vip-cli, pull requests merged in 2022-08, with the labels that each got.

#1067 FORNO-1244: SQL Import: Increase max import size for launched sites to 1GB
  src/lib/site-import/db-file-import.js
Labels: [Status] Needs Review

#1072 [dev-env] Include stack trace to error tracking
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1074 [dev-env] update lando dependency
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1070 [dev-env] validate client code - look for specific subdirectories
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1068 Software Management: Get settings
  package.json
  src/bin/vip-config-software-get.js
  src/bin/vip-config-software.js
  src/bin/vip-config.js
  src/lib/api/app.js
  src/lib/cli/command.js
  src/lib/config/software.js
Labels: [Status] Ready to Merge

#1073 [dev-env] e2e Windows tests
  .github/workflows/tests.yml
  __tests__/e2e_test.bat
Labels: [Status] Ready to Merge

#1078 SQL Import: Fix multisite primary domain validation
  __tests__/lib/validations/is-multisite-domain-mapped.js
  src/lib/validations/is-multisite-domain-mapped.js
  src/lib/validations/site-type.js
Labels: [Status] Ready to Merge

#1080 [dev-env] switch name to slug in info table
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#1079 [dev-env] support multiple falsy values
  src/bin/vip-dev-env-create.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1077 [dev-env] Remove app.env support from non-create command
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-info.js
  src/lib/cli/command.js
  src/lib/cli/userError.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/types.js
Labels: [Status] Has Feedback, [Status] Needs Review

#1084 Update/sw get tweaks
  src/bin/vip-config-software-get.js
  src/lib/config/software.js
Labels: [Status] Needs Review

#1087 Increase the limit of sql file from 1GB to 5GB for SQL Imports
  src/lib/site-import/db-file-import.js
Labels: [Status] Ready to Merge
