Repository Automattic/vip-cli, pull requests merged in 2022-10, with the labels that each got.

#1124 [dev-env] Supress Setup wizard during update
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1126 Update memcached to 1.6-alpine3.16
  assets/dev-env.lando.template.yml.ejs
Labels: [Status] Needs Review

#1120 Update php-fpm image names
  src/lib/constants/dev-environment.js
Labels: [Status] Needs Review

#1125 add validation output
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1130 Update/exec help
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-exec.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1114 [dev-env] Verify current user is a docker user
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1098 Include options into reading software config
  src/bin/vip-config-software-get.js
  src/lib/config/software.js
Labels: [Status] Ready to Merge

#1135 [dev-env] Make xdebug config not break during wp update
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1131 FORNO-1296: SQL Import - Add ALTER TABLE statement validation
  __fixtures__/validations/bad-sql-dump.sql
  __tests__/lib/validations/sql.js
  src/lib/validations/sql.js
Labels: [Status] Ready to Merge

#1136 FORNO-1328: SQL Import: Add validation for unique_checks being disabled
  __fixtures__/validations/bad-sql-dump.sql
  __tests__/lib/validations/sql.js
  src/lib/validations/sql.js
Labels: [Status] Needs Docs

#1121 Add support for custom PHP images
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1133 Add PHP 8.2 image
  src/lib/constants/dev-environment.js
Labels: [Type] Enhancement

#1129 Fix ESLint/Flow/SonarScan issues
  __tests__/lib/cli/config.js
  __tests__/lib/dev-environment/dev-environment-core.js
  src/bin/vip-dev-env-import-sql.js
  src/lib/api.js
  src/lib/config/software.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1141 SQL validation: Change formatting to make it more readable
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#1138 [dev-env] Update/rename app code and mu-plugins
  assets/dev-env.lando.template.yml.ejs
Labels: [Status] Ready to Merge

#1132 [PIE-3105] Update VIP-CLI command line output
  src/bin/vip.js
Labels: [Status] Ready to Merge

#1144 fix: Suppress ES security-related warnings
  assets/dev-env.lando.template.yml.ejs
Labels: [Type] Enhancement, [Status] Ready to Merge

#1146 fix(dev-env): Resolve the "xdebugConfig is not defined" issue
  src/lib/dev-environment/dev-environment-core.js
Labels: [Type] Bug, [Status] Needs Review

#1143 [dev-env] adds default for wordpress version prompt
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge
