Repository Automattic/vip-cli, pull requests merged in 2022-09, with the labels that each got.

#1083 Software Management: Update
  package.json
  src/bin/vip-config-software-get.js
  src/bin/vip-config-software-update.js
  src/bin/vip-config-software.js
  src/lib/app.js
  src/lib/cli/command.js
  src/lib/config/software.js
  src/lib/constants/vipgo.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/user-error.js
Labels: [Status] Needs Review

#1090 Add tracking to software update
  src/bin/vip-config-software-update.js
Labels: [Status] Needs Review

#1091 Extract http helper into standalone function
  src/lib/analytics/clients/pendo.js
  src/lib/api.js
  src/lib/api/http.js
Labels: [Status] Needs Review

#1093 [dev-env] use latest proxy image
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1097 Don't pipe output through less
  src/lib/cli/command.js
  src/lib/cli/pager.js
Labels: [Status] Ready to Merge

#1092 Improve login + logout
  src/bin/vip.js
  src/lib/logout.js
Labels: [Status] Needs Review

#1099 Add @app.env to commands help
  __tests__/bin/vip-config-envvar-delete.js
  __tests__/bin/vip-config-envvar-get-all.js
  __tests__/bin/vip-config-envvar-get.js
  __tests__/bin/vip-config-envvar-list.js
  __tests__/bin/vip-config-envvar-set.js
  src/bin/vip-config-envvar-delete.js
  src/bin/vip-config-envvar-get-all.js
  src/bin/vip-config-envvar-get.js
  src/bin/vip-config-envvar-list.js
  src/bin/vip-config-envvar-set.js
  src/bin/vip-config-software-get.js
  src/bin/vip-config-software-update.js
  src/bin/vip-config-software.js
Labels: [Status] Needs Review

#1096 [dev-env] Supports extended information table
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-info.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1106 Using http module instead of already decommissioned API.apiFetch function
  src/lib/client-file-uploader.js
Labels: [Status] Needs Review

#1049 Fix security issues
  .flowconfig
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review, [Status] Stale

#1104 [dev-env] fetch php and wordpress versions for creation wizard
  __tests__/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1119 Use --yes instead of --force
  src/bin/vip-config-software-update.js
Labels: [Status] Needs Review

#1111 [dev-env] prompt for es index after db import
  src/bin/vip-dev-env-import-sql.js
Labels: [Status] Needs Review
