Repository Automattic/vip-cli, pull requests merged in 2022-05, with the labels that each got.

#1018 [dev-env] enable lando debug on `--debug`
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1020 More tracking
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-update.js
  src/lib/tracker.js
Labels: [Status] Needs Review

#1012 Update VIP-CLI release process
  CONTRIBUTING.md
Labels: [Status] Needs Review

#1019 Unifies lando and other dev-env debug logs
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#1023 [dev-env] Skip the trunk from the prompt about the latest available WordPress versions
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1021 [dev-env] Add login info and documentation link to `dev-env info`
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#1026 [dev-env] adds tracking to stop subcommand
  src/bin/vip-dev-env-stop.js
Labels: [Status] Needs Review

#1030 [dev-env] Fix failure tracking
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1029 Adds Pendo analytics client
  src/lib/analytics/clients/pendo.js
  src/lib/analytics/index.js
  src/lib/tracker.js
Labels: [Status] Needs Review

#1033 [dev-env] Bump lando in order to support node 18
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#999 Add Feature to Support HTTPS/HTTP/NO_PROXY Settings from System
  __tests__/lib/http/proxy-agent.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-wp.js
  src/lib/api.js
  src/lib/http/proxy-agent.js
  src/lib/http/socks-proxy-agent.js
Labels: [Status] Has Feedback, [Status] Needs Review

#1036 Move DO_NOT_TRACK handling to Analytics lib
  __tests__/lib/analytics/clients/tracks.js
  __tests__/lib/analytics/index.js
  src/lib/analytics/clients/stub.js
  src/lib/analytics/clients/tracks.js
  src/lib/analytics/index.js
Labels: [Status] Needs Review

#1032 Introduce .nvmrc and npm check on publish
  .nvmrc
  .publishrc
  CONTRIBUTING.md
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1037 [dev-env] only record the php version numbers
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1035 New config module
  .gitignore
  .npmignore
  __tests__/lib/cli/config.js
  helpers/prepare-config.js
  package.json
  src/bin/vip.js
  src/lib/cli/config.js
  src/lib/rollbar.js
  src/lib/tracker.js
Labels: [Status] Needs Review

#1040 [dev-env] track dev-env start time in seconds
  src/bin/vip-dev-env-start.js
Labels: [Status] Has Feedback

#1043 [dev-env] add docker-compose v2 support
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge
