Repository Automattic/vip-cli, pull requests merged in 2022-02, with the labels that each got.

#964 [dev-env] Validate sql on import
  __fixtures__/validations/bad-sql-dev-env.sql
  __tests__/lib/validations/sql.js
  npm-shrinkwrap.json
  src/bin/vip-dev-env-import-sql.js
  src/lib/validations/sql.js
Labels: [Status] Ready to Merge

#968 Update minimum Node version
  .circleci/config.yml
  babel.config.js
  package.json
Labels: [Status] Needs Review

#967 Do not use /tmp as a userConfRoot
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Bug

#971 [dev-env] Use custom add user command
  src/bin/vip-dev-env-import-sql.js
Labels: [Status] Ready to Merge

#970 Do not use /tmp as a userConfRoot
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#973 [dev-env] update Nginx image
  assets/dev-env.lando.template.yml.ejs
Labels: [Status] Ready to Merge

#974 Corrections of text for -h menu in dev-env create
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
Labels: [Status] Ready to Merge

#977 Try to fix Flow errors
  .circleci/config.yml
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review
