Repository Automattic/vip-cli, pull requests merged in 2022-12, with the labels that each got.

#1188 fix: Make bin files executables
  src/bin/vip-import-media-abort.js
  src/bin/vip-import-media-status.js
  src/bin/vip-import.js
Labels: [Status] Ready to Merge

#1170 [dev-env] Substitute the check for forward slash to with a cross-platform regex when processing component argument value
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1179 feat(dev-env): Do not prompt for missing values if stdin is not a TTY
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge, [Status] Needs Docs

#1189 refactor(dev-env): Bootstrap Lando only once
  __tests__/lib/dev-environment/dev-environment-core.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1193 Fix regression in vip dev-env import sql related to the fact we don't mount User's home dir anymore
  __tests__/lib/dev-environment/dev-environment-core.js
  package.json
  src/bin/vip-dev-env-import-sql.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1204 Dev-env: Update ES to 7.17.8 to match prod
  assets/dev-env.lando.template.yml.ejs
Labels: [Status] Ready to Merge

#1202 fix(dev-env): Do not load integrations for Acquia, Lagoon, Pantheon
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1206 fix(dev-env): await handleCLIException() and set proper exit code
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1212 fix(dev-env): Errors should go to stderr, not stdout
  src/lib/cli/exit.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1208 feat(dev-env): Add quiet mode to `vip dev-env exec`
  src/bin/vip-dev-env-exec.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Ready to Merge

#1214 chore(deps): Update babel to 7.20
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1213 chore(deps): Update jest to 29.3.1 and nock to 13.2.9
  jest.config.js
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1217 Add filename validation to sql import
  src/bin/vip-import-sql.js
Labels: [Status] Ready to Merge

#1218 Fix a grammatical mistake in the error message
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1219 fix(dev-env): Fix search/replace on SQL file import
  src/lib/dev-environment/dev-environment-core.js
Labels: [Type] Bug, [Status] Needs Review

#1226 Add some additional info on installation
  README.md
Labels: [Status] Needs Review

#1223 chore(deps): Update flow to 0.196.3
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1222 chore(deps): Update babel to 7.20.7
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1203 test(dev-env): Add E2E tests for dev env
  .eslintrc.json
  .github/workflows/devenv-e2e.yml
  __fixtures__/dev-env-e2e/empty.sql
  __fixtures__/dev-env-e2e/fail-validation.sql
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/002-destroy.spec.js
  __tests__/devenv-e2e/003-start.spec.js
  __tests__/devenv-e2e/004-stop.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/006-list.spec.js
  __tests__/devenv-e2e/007-info.spec.js
  __tests__/devenv-e2e/008-exec.spec.js
  __tests__/devenv-e2e/009-import-media.spec.js
  __tests__/devenv-e2e/010-import-sql.spec.js
  __tests__/devenv-e2e/helpers/cli-test.js
  __tests__/devenv-e2e/helpers/commands.js
  __tests__/devenv-e2e/helpers/docker-utils.js
  __tests__/devenv-e2e/helpers/utils.js
  __tests__/devenv-e2e/jest/jest.config.js
  __tests__/devenv-e2e/jest/sequencer.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-import-media.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1183 feat(dev-env): Add support for the most recent Lando
  npm-shrinkwrap.json
  package.json
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1211 fix(dev-env)!: remove support for statsd
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/types.js
Labels: [Status] Keep

#1224 fix(tests): do not fail when `DO_NOT_TRACK` is set
  __tests__/lib/analytics/index.js
Labels: [Type] Bug, [Status] Ready to Merge
