Repository Automattic/vip-cli, pull requests merged in 2022-11, with the labels that each got.

#1163 Pull correct environment's details from API when displaying Multisite SQL Import preflight details
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1164 Fix regExp to categorize multisite tables during SQL Imports
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1165 Add caching type policy for `WPSite` data
  src/lib/api.js
Labels: [Status] Needs Review

#1166 Prep 2.22.0
  .github/workflows/tests.yml
  assets/dev-env.lando.template.yml.ejs
  npm-shrinkwrap.json
  package.json
  src/bin/vip-import-sql.js
  src/lib/api.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1167 dev-env: Fix bug in getVersionList() when path doesn't exist
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge

#1095 Harmonia Pre Deploy Validation: Add `validate` command
  npm-shrinkwrap.json
  package.json
  src/bin/vip-validate-preflight.js
  src/bin/vip-validate.js
  src/bin/vip.js
  src/lib/api.js
Labels: [Status] Needs Review, [Status] Ready to Merge

#1169 Preflight Validation: Change return code on error
  src/bin/vip-validate-preflight.js
Labels: [Status] Needs Review

#1171 Prep: 2.23.0
  CHANGELOG.md
  __tests__/lib/dev-environment/dev-environment-core.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-validate-preflight.js
  src/bin/vip-validate.js
  src/bin/vip.js
  src/lib/api.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1181 fix(dev-env): Set SQL_MODE to match our production environment
  assets/dev-env.lando.template.yml.ejs
Labels: [Type] Bug, [Status] Ready to Merge

#1180 fix(dev-env): Fix a typo in parameter description
  src/bin/vip-dev-env-start.js
Labels: [Status] Needs Review

#1175 Dev-env: Throw error if more than one environment found when starting
  src/bin/vip-dev-env-start.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1182 Dev-env: Throw UserError in getEnvironmentName() instead and default to first one if only one env
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-start.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1184 Validate Preflight: Allow preflight checks to execute without explicit app and/or env
  src/bin/vip-validate-preflight.js
  src/bin/vip-validate.js
Labels: [Status] Needs Review

#1186 feat(dev-env): Do not mount home directory into containers
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1185 feat(dev-env): Add support for MailHog
  __tests__/e2e_test.bat
  __tests__/lib/dev-environment/dev-environment-cli.js
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-lando.js
  src/lib/dev-environment/types.js
Labels: [Type] Enhancement, [Status] Ready to Merge
