Repository Automattic/vip-cli, pull requests merged in 2023-08, with the labels that each got.

#1477 Fetch environment name from server to fix environment selector label
  src/bin/vip-import-media-abort.js
  src/bin/vip-import-media-status.js
  src/bin/vip-import-sql-status.js
Labels: [Status] Needs Review

#1479 chore(dev-deps): update jest-related packages to 29.6.2
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1480 chore(deps): update node-fetch to 2.6.12
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1481 chore(deps): update socket.io-client to 4.7.2
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1482 chore(deps): update enquirer to 2.4.1
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1458 Add warning confirmation when there's not enough space on disk.
  __tests__/commands/dev-env-sync-sql.js
  __tests__/commands/export-sql.js
  __tests__/lib/backup-storage-availability/backup-storage-availability.ts
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-sync-sql.js
  src/commands/dev-env-sync-sql.js
  src/commands/export-sql.js
  src/lib/backup-storage-availability/backup-storage-availability.ts
  src/lib/backup-storage-availability/docker-machine-not-found-error.ts
  src/lib/cli/format.ts
  src/lib/cli/progress.ts
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Status] Needs Review

#1487 fix(dev-env): display ports exposed by services
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Type] Bug

#1491 chore(dev-deps): update eslint from 8.43.0 to 8.47.0
  npm-shrinkwrap.json
Labels: [Status] Retro Review, Upstream Dependency

#1486 chore(dev-deps): update babel-related packages
  npm-shrinkwrap.json
  package.json
Labels: [Status] Retro Review, Upstream Dependency

#1484 feat(backup): Add vip backup db command
  __tests__/commands/backup-db.ts
  __tests__/lib/cli/format.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-backup-db.ts
  src/bin/vip-backup.ts
  src/bin/vip.js
  src/commands/backup-db.ts
  src/commands/export-sql.js
  src/lib/cli/format.ts
Labels: [Status] Needs Review, [Status] Needs Docs
