Repository Automattic/vip-cli, pull requests merged in 2023-11, with the labels that each got.

#1540 chore(deps): update jwt-decode from 3.1.2 to 4.0.0
  npm-shrinkwrap.json
  package.json
  src/lib/token.ts
Labels: Upstream Dependency

#1541 chore(dev-deps): update nock from 13.3.4 to 13.3.7
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1545 chore(deps): replace deprecated `json2csv` with `@json2csv/plainjs`
  .nvmrc
  __tests__/bin/vip-logs.js
  __tests__/bin/vip-slowlogs.js
  npm-shrinkwrap.json
  package.json
  src/lib/cli/format.ts
Labels: [Status] Needs Review

#1556 chore(dev-deps): update eslint from 8.52.0 to 8.54.0
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1555 chore(deps): replace the deprecated `opn` with `open`
  npm-shrinkwrap.json
  package.json
  src/bin/vip.js
Labels: [Status] Needs Review

#1577 Updating ESLint config
  .eslintrc.js
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/npm-prepare-release.yml
  .prettierignore
  src/lib/app-slowlogs/app-slowlogs.generated.d.ts
  tsconfig.json
  types/enquirer/index.d.ts
  types/lando/lib/app.d.ts
  types/lando/lib/art.d.ts
  types/lando/lib/bootstrap.d.ts
  types/lando/lib/cache.d.ts
  types/lando/lib/cli.d.ts
  types/lando/lib/compose.d.ts
  types/lando/lib/config.d.ts
  types/lando/lib/daemon.d.ts
  types/lando/lib/docker.d.ts
  types/lando/lib/engine.d.ts
  types/lando/lib/env.d.ts
  types/lando/lib/error.d.ts
  types/lando/lib/events.d.ts
  types/lando/lib/factory.d.ts
  types/lando/lib/formatters.d.ts
  types/lando/lib/lando.d.ts
  types/lando/lib/logger.d.ts
  types/lando/lib/metrics.d.ts
  types/lando/lib/plugins.d.ts
  types/lando/lib/router.d.ts
  types/lando/lib/scan.d.ts
  types/lando/lib/shell.d.ts
  types/lando/lib/table.d.ts
  types/lando/lib/utils.d.ts
  types/lando/lib/yaml.d.ts
  types/lando/plugins/lando-core/lib/utils.d.ts
  types/lando/plugins/lando-tooling/lib/build.d.ts
Labels: [Type] Enhancement

#1559 Restructure and refine documentation + add missing tests
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/windows-tests.yml
  .prettierignore
  CONTRIBUTING.md
  README.md
  docs/ARCHITECTURE.md
  docs/CHANGELOG.md
  docs/CONTRIBUTING.md
  docs/DEBUGGING.md
  docs/RELEASING.md
  docs/SECURITY.md
  docs/SETUP.md
  docs/TESTING.md
Labels: [Type] Enhancement

#1591 Fix database backup URL in error message
  src/commands/export-sql.js
Labels: [Pri] Normal

#1537 Add vip dev-env purge command logic
  package.json
  src/bin/vip-dev-env-purge.js
  src/bin/vip-dev-env.js
Labels: [Status] Needs Review
