Repository Automattic/vip-cli, pull requests merged in 2023-06, with the labels that each got.

#1390 chore(deps): Update @automattic/vip-search-replace to 1.1.1
  npm-shrinkwrap.json
  package.json
Labels: [Status] Retro Review

#1391 refactor: Convert lib to TypeScript
  src/bin/vip-import-sql.js
  src/commands/dev-env-sync-sql.js
  src/lib/api/http.ts
  src/lib/client-file-uploader.ts
  src/lib/logout.ts
  src/lib/read-file.js
  src/lib/read-file.ts
  src/lib/search-and-replace.ts
  src/lib/user-error.js
  src/lib/user-error.ts
Labels: [Status] Needs Review

#1398 Fix coverage generation
  __tests__/lib/cli/envAlias.js
  babel.config.js
  package.json
Labels: [Status] Needs Review

#1394 FORNO-1609: Combine all error events into one error event
  src/bin/vip-dev-env-sync-sql.js
  src/commands/dev-env-sync-sql.js
  src/commands/export-sql.js
Labels: [Status] Needs Review

#1397 feature(dev-env): Add ability to sync multisites
  __tests__/commands/dev-env-sync-sql.js
  src/bin/vip-dev-env-sync-sql.js
  src/commands/dev-env-sync-sql.js
Labels: [Status] Needs Review

#1402 chore(dev-deps): Update Babel-related packages to 7.22.5
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1403 chore(dev-deps): Update ESLint-related packages
  __tests__/lib/validations/utils.js
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1404 chore(dev-deps): Update TypeScript-related packages
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1406 chore(deps): Replace keytar with @postman/node-keytar
  npm-shrinkwrap.json
  package.json
  src/lib/keychain/secure.ts
Labels: Upstream Dependency

#1407 chore(dev-deps): Update flow-bin from 0.206.0 to 0.208.0
  flow-typed/npm/@apollo/client_v3.x.x.js
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1409 chore(deps): Update semver to 7.5.2
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1410 chore(dev-deps): Update flow-bin to 0.209.0
  .gitattributes
  .npmignore
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1396 Migrate dev-environment-core to TypeScript
  src/lib/constants/dev-environment.ts
  src/lib/constants/file-size.ts
  src/lib/constants/vipgo.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/types.ts
  tsconfig.json
  types/copy-dir/index.d.ts
  types/lando/index.d.ts
  types/lando/lib/app.d.ts
  types/lando/lib/lando.d.ts
Labels: [Status] Needs Review

#1418 chore(deps): Update semver from 7.5.2 to 7.5.3
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1417 chore(dev-deps): Update eslint from 8.42.0 to 8.43.0
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1422 chore(dev-deps): update flow-bin from 0.209.0 to 0.210.0
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1423 chore(deps): update socket.io-client from 4.6.2 to 4.7.0
  npm-shrinkwrap.json
Labels: [Status] Needs Review, Upstream Dependency
