Repository Automattic/vip-cli, pull requests merged in 2023-09, with the labels that each got.

#1488 fix: do not abort if a temporary directory cannot be removed on exit
  src/lib/utils.ts
Labels: [Status] Needs Review

#1500 chore(dev-deps): update babel-related packages
  npm-shrinkwrap.json
  package.json
Labels: [Status] Retro Review, Upstream Dependency

#1501 chore(deps): update jest-related packages
  npm-shrinkwrap.json
Labels: [Status] Retro Review, Upstream Dependency

#1502 chore(dev-deps): update flow-bin to 0.216.1
  npm-shrinkwrap.json
  package.json
Labels: [Status] Retro Review, Upstream Dependency

#1503 chore(dev-deps): update nock to 13.3.3
  npm-shrinkwrap.json
  package.json
Labels: [Status] Retro Review, Upstream Dependency

#1507 Allow imports for all sites with databases
  __tests__/lib/site-import.js
  src/bin/vip-import-sql.js
  src/lib/constants/vipgo.ts
  src/lib/site-import/db-file-import.ts
Labels: [Status] Needs Review

#1496 fix(dev-env): update certificate Common Name
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Status] Needs Review, [Status] Needs Docs

#1508 chore(dev-deps): update jest-related packages to 29.7.0
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1509 chore(dev-deps): update eslint from 8.47.0 to 8.49.0
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1510 chore(deps): update uuid from 9.0.0 to 9.0.1
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1512 chore(deps): update node-fetch from 2.6.12 to 2.7.0
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1511 chore(deps): update graphql-tag from 2.12.5 to 2.12.6
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1516 chore(dev-deps): update eslint from 8.49.0 to 8.50.0
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1521 Fix link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: [Type] Enhancement, [Pri] Normal
