Repository Automattic/vip-cli, pull requests merged in 2023-05, with the labels that each got.

#1123 [dev-env] Add VSCode workspace config on start
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-start.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Has Feedback

#1347 [dev-env] add vscode flag to event tracking for start
  src/bin/vip-dev-env-start.js
Labels: [Status] Ready to Merge

#1364 fix(dev-env): Fix "Cannot read properties of undefined" in `preProcessInstanceData()`
  src/lib/constants/dev-environment.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Type] Bug

#1361 chore(dev-deps): Update packages related to linting
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1365 chore(deps): Fix CVE-2023-32695
  npm-shrinkwrap.json
Labels: [Status] Needs Review, Upstream Dependency

#1360 chore(dev-deps): Update flow-bin from 0.205.1 to 0.206.0
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review, Upstream Dependency

#1357 chore(deps): Update semver from 7.5.0 to 7.5.1
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1356 fix(dev-env): Handle `--media-redirect-domain` in `vip dev-env update`
  src/lib/dev-environment/dev-environment-configuration-file.js
  src/lib/dev-environment/types.js
Labels: [Type] Bug

#1362 Add vip export sql command
  __tests__/lib/cli/format.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-export-sql.js
  src/bin/vip-export.js
  src/bin/vip.js
  src/commands/export-sql.js
  src/lib/cli/format.js
  src/lib/cli/progress.js
  src/lib/tracker.js
  src/lib/utils.js
Labels: [Status] Needs Review

#1354 fix(dev-env): Properly handle non-string arguments in resolvePhpVersion()
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-cli.js
Labels: [Type] Bug

#1368 Refactor Export SQL command tracks event names
  src/bin/vip-export-sql.js
  src/commands/export-sql.js
  src/lib/cli/format.js
Labels: [Status] Ready to Merge

#1372 fix(export): Make vip-export-sql.js executable
  src/bin/vip-export-sql.js
Labels: [Type] Bug, [Status] Needs Review

#1334 Dev-env: Allow --multisite to accept boolean, subdirectory, or subdomain values
  __tests__/lib/dev-environment/dev-environment-cli.js
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-create.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1370 fix: Fix issues found by SonarCloud
  __tests__/lib/cli/apiConfig.js
  __tests__/lib/cli/config.js
  __tests__/lib/token.js
  src/bin/vip-import-validate-sql.js
  src/bin/vip-wp.js
  src/bin/vip.js
  src/lib/api/feature-flags.js
  src/lib/config/software.js
  src/lib/dev-environment/dev-environment-lando.js
  src/lib/media-import/status.js
  src/lib/site-import/status.js
  src/lib/token.js
  src/lib/tracker.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review

#1264 Add dev-env-sync-sql command
  __tests__/commands/dev-env-sync-sql.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-sync-sql.js
  src/bin/vip-dev-env-sync.js
  src/bin/vip-dev-env.js
  src/commands/dev-env-sync-sql.js
Labels: [Status] Needs Review, [Status] Keep

#1381 refactor: Convert lib/cli and dependencies to TypeScript
  __tests__/lib/cli/envAlias.ts
  babel.config.js
  npm-shrinkwrap.json
  package.json
  src/lib/api.ts
  src/lib/api/feature-flags.ts
  src/lib/cli/apiConfig.ts
  src/lib/cli/envAlias.ts
  src/lib/cli/exit.js
  src/lib/cli/exit.ts
  src/lib/cli/format.ts
  src/lib/cli/progress.ts
  src/lib/cli/prompt.ts
  src/lib/cli/repo.js
Labels: [Status] Needs Review

#1382 test: Reduce noise from tests
  __tests__/bin/vip-import-sql.js
  __tests__/commands/dev-env-sync-sql.js
  __tests__/commands/export-sql.js
  __tests__/lib/app-logs/app-logs.js
  __tests__/lib/cli/apiConfig.js
  __tests__/lib/dev-environment/dev-environment-cli.js
Labels: [Status] Needs Review

#1383 fix(dev-env): Pull uniqueLabel field from backend
  src/bin/vip-export-sql.js
Labels: [Status] Needs Review
