Repository Automattic/vip-cli, pull requests merged in 2023-01, with the labels that each got.

#1201 fix(dev-env): Do not check env is up for every action
  __tests__/devenv-e2e/009-import-media.spec.js
  __tests__/devenv-e2e/helpers/utils.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1209 refactor(dev-env): Run health checks in parallel
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1229 fix(dev-env): Perform ES healthcheck properly
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Bug

#1230 Dev-env: Fix ES service reference
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1231 fix(dev-env): Inherit stdio descriptors for 'dev-env exec'
  __tests__/devenv-e2e/008-exec.spec.js
  src/bin/vip-dev-env-exec.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1232 fix(dev-env): Make environment existence check more robust
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/002-destroy.spec.js
  __tests__/devenv-e2e/003-start.spec.js
  __tests__/devenv-e2e/004-stop.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/006-list.spec.js
  __tests__/devenv-e2e/008-exec.spec.js
  __tests__/devenv-e2e/009-import-media.spec.js
  __tests__/devenv-e2e/010-import-sql.spec.js
  __tests__/devenv-e2e/helpers/utils.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Ready to Merge

#1235 Prepare 2.25.0
  .eslintrc.json
  .flowconfig
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/devenv-e2e.yml
  .gitignore
  .npmignore
  .publishrc
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  __fixtures__/dev-env-e2e/empty.sql
  __fixtures__/dev-env-e2e/fail-validation.sql
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/002-destroy.spec.js
  __tests__/devenv-e2e/003-start.spec.js
  __tests__/devenv-e2e/004-stop.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/006-list.spec.js
  __tests__/devenv-e2e/007-info.spec.js
  __tests__/devenv-e2e/008-exec.spec.js
  __tests__/devenv-e2e/009-import-media.spec.js
  __tests__/devenv-e2e/010-import-sql.spec.js
  __tests__/devenv-e2e/helpers/cli-test.js
  __tests__/devenv-e2e/helpers/commands.js
  __tests__/devenv-e2e/helpers/docker-utils.js
  __tests__/devenv-e2e/helpers/utils.js
  __tests__/devenv-e2e/jest/jest.config.js
  __tests__/devenv-e2e/jest/sequencer.js
  __tests__/lib/analytics/index.js
  __tests__/lib/dev-environment/dev-environment-core.js
  assets/dev-env.lando.template.yml.ejs
  jest.config.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-update.js
  src/bin/vip-import-sql.js
  src/lib/cli/command.js
  src/lib/cli/exit.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
  src/lib/dev-environment/types.js
Labels: [Status] Ready to Merge

#1247 Add library to facilitate SQL backup export
  __tests__/lib/sql-export.js
  src/lib/sql-export.js
  src/lib/utils.js
Labels: [Status] Needs Review

#1251 Fix lint errors
  __tests__/lib/sql-export.js
  src/lib/sql-export.js
  src/lib/utils.js
Labels: [Status] Ready to Merge

#1259 Add notifications commands to package.json
  package.json
Labels: [Status] Needs Review

#1250 feat(dev-env): Implement upgrade path for changes affecting .lando.yml
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/006-list.spec.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Enhancement, [Status] Ready to Merge

#1261 fix(dev-env): Gracefully handle failures to fetch WP versions
  src/lib/dev-environment/dev-environment-core.js
Labels: [Type] Bug, [Status] Ready to Merge

#1263 Dev-env: Do not prompt to update WP version if trunk is used
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1253 Remove use-database statement check
  __fixtures__/validations/bad-sql-dev-env.sql
  __tests__/lib/dev-environment/dev-environment-core.js
  __tests__/lib/validations/sql.js
  src/bin/vip-dev-env-import-sql.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/search-and-replace.js
  src/lib/validations/sql.js
Labels: [Status] Needs Review, [Status] Needs Docs

#1266 fix(dev-env): Fix incorrect working directory when vip dev-env exec is run from a 8 level deep directory
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Bug

#1258 fix(dev-env): Get more verbose logs from Lando in debug mode
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Docs

#1237 Skip requoting if the arg is a valid JSON Object
  __tests__/lib/cli/format.js
  src/lib/cli/format.js
Labels: [Status] Needs Review

#1270 Dev-env: Fix WordPress version inputs for major releases ending in .0
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
Labels: [Status] Ready to Merge
