Repository Automattic/vip-cli, pull requests merged in 2023-02, with the labels that each got.

#1274 Run validation on filename & not on full filepath
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1273 Add library for the dev-env-sync-sql command
  __tests__/commands/dev-env-sync-sql.js
  __tests__/commands/export-sql.js
  src/bin/vip-dev-env-import-sql.js
  src/commands/dev-env-import-sql.js
  src/commands/dev-env-sync-sql.js
  src/commands/export-sql.js
  src/lib/client-file-uploader.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/search-and-replace.js
  src/lib/utils.js
Labels: [Status] Needs Review

#1271 refactor(dev-env): Switch to mysql:8
  __fixtures__/dev-env-e2e/.lando_mariadb.yml
  __fixtures__/dev-env-e2e/instance_data_mariadb.json
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-update.js
  src/lib/constants/dev-environment.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Docs

#1276 [dev-env] Add ability to override default options for lando with a global Lando config.yml
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Docs

#1277 Fix the PassThrough class import
  src/lib/client-file-uploader.js
Labels: [Status] Needs Review

#1278 Prepare v2.26.2
  src/lib/client-file-uploader.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#1173 Add dev-env configuration file
  __tests__/devenv-e2e/011-configuration-file.spec.js
  __tests__/devenv-e2e/helpers/utils.js
  __tests__/lib/dev-environment/dev-environment-cli.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-update.js
  src/commands/dev-env-import-sql.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-configuration-file.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Docs

#1284 test: Do not mock `localStorage` if `global.localStorage` is defined
  __tests__/lib/keychain.js
Labels: [Type] Bug, [Status] Needs Review

#1283 fix(dev-env): Add missing `await`
  src/bin/vip-dev-env-logs.js
Labels: [Type] Bug

#1267 feat(dev-env): Add `vip dev-env shell` command
  __tests__/devenv-e2e/012-shell.spec.js
  __tests__/devenv-e2e/helpers/commands.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-shell.js
  src/bin/vip-dev-env.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review, [Status] Needs Docs

#1286 fix(dev-env): Provide Flow typings for `landoLogs()`
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Bug

#1287 fix(dev-env): Pull fresh images for new environments
  src/lib/dev-environment/dev-environment-lando.js
  src/lib/dev-environment/types.js
Labels: [Status] Ready to Merge
