Repository Automattic/vip-cli, pull requests merged in 2023-03, with the labels that each got.

#1291 Dev-env: Fix silent failing when passing invalid subcommand
  src/bin/vip-dev-env.js
Labels: [Status] Ready to Merge

#1292 Fix requiredArgs for other vip commands
  src/bin/vip-cache.js
  src/bin/vip-config-envvar.js
  src/bin/vip-validate.js
Labels: [Status] Ready to Merge

#1294 chore(dev-deps): Update Jest-related packages to 29.4.3
  npm-shrinkwrap.json
  package.json
Labels: [Status] Ready to Merge

#1302 fix(ci): Do not prompt for WP update
  .github/workflows/devenv-e2e.yml
  __tests__/devenv-e2e/003-start.spec.js
  __tests__/devenv-e2e/helpers/utils.js
Labels: [Type] Bug, [Status] Ready to Merge

#1306 chore(dev-deps): Forcefully update lodash for publish-please to 4.17.21
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1307 chore(dev-deps): Update nock to 13.3.0
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1308 chore(dev-deps): Update dockerode to 3.3.5
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1309 chore(dev-deps): Update flow-bin to 0.202.1
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1312 chore(dev-deps): Update prettier to 2.8.7
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1310 chore(deps): Update ejs to 3.1.9
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1311 chore(dev-deps): Update eslint to 8.36.0
  npm-shrinkwrap.json
Labels: [Status] Needs Review

#1314 chore(deps): Update socket.io-client to 4.6.1
  npm-shrinkwrap.json
Labels: [Status] Needs Review
