Repository Automattic/vip-cli, pull requests merged in 2023-10, with the labels that each got.

#1523 SQL Import Status: Ensure we pull site type ID from server for validation
  src/bin/vip-import-sql-status.js
Labels: [Status] Needs Review

#1531 chore(dev-deps): update nock from 13.3.3 to 13.3.4
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1529 chore(dev-deps): update eslint from 8.50.0 to 8.51.0
  npm-shrinkwrap.json
Labels: Upstream Dependency

#1532 chore(dev-deps): update dockerode from 3.3.4 to 4.0.0
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1528 chore(dev-deps): update Babel-related stuff to 7.23
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1533 FORNO-1704: SQL Import - Improve handling of compressed files
  __fixtures__/dev-env-e2e/fail-validation.sql.gz
  __fixtures__/validations/bad-sql-dump.sql.gz
  __fixtures__/validations/empty.zip
  __tests__/bin/vip-import-sql.js
  __tests__/devenv-e2e/010-import-sql.spec.js
  __tests__/lib/validations/sql.js
  src/bin/vip-import-sql.js
  src/commands/dev-env-import-sql.js
  src/lib/client-file-uploader.ts
  src/lib/validations/sql.ts
Labels: [Status] Needs Docs

#1535 FORNO-1677: Fix dev env network site domains
  __tests__/commands/dev-env-sync-sql.js
  src/commands/dev-env-sync-sql.js
Labels: [Status] Needs Review
