Repository Automattic/vip-cli, pull requests merged in 2023-07, with the labels that each got.

#1427 Remove unnecessary comment
  CONTRIBUTING.md
Labels: [Status] Needs Review

#1411 feature(export): Add ability to generate a new backup when exporting SQL
  __tests__/commands/backup-db.ts
  src/bin/vip-export-sql.js
  src/commands/backup-db.ts
  src/commands/dev-env-sync-sql.js
  src/commands/export-sql.js
  src/lib/tracker.ts
  src/lib/utils.ts
Labels: [Status] Needs Review

#1430 Update changelog for 2.32.0 release
  CHANGELOG.md
Labels: [Status] Needs Review

#1429 Add codegen for GraphQL queries
  .eslintignore
  .gitignore
  CONTRIBUTING.md
  codegen.ts
  noImplicitAnyImportBypass.d.ts
  package.json
  src/bin/vip-app-list.generated.d.ts
  src/bin/vip-import-media-abort.generated.d.ts
  src/bin/vip-import-media.generated.d.ts
  src/bin/vip-import-sql.generated.d.ts
  src/bin/vip-sync.generated.d.ts
  src/bin/vip-validate-preflight.generated.d.ts
  src/bin/vip-wp.generated.d.ts
  src/commands/export-sql.generated.d.ts
  src/graphqlTypes.d.ts
  src/lib/api/cache-purge.generated.d.ts
  src/lib/api/feature-flags.generated.d.ts
  src/lib/api/http.ts
  src/lib/api/user.generated.d.ts
  src/lib/app-logs/app-logs.generated.d.ts
  src/lib/app-logs/app-logs.ts
  src/lib/config/software.generated.d.ts
  src/lib/envvar/api-delete.generated.d.ts
  src/lib/envvar/api-get-all.generated.d.ts
  src/lib/envvar/api-list.generated.d.ts
  src/lib/envvar/api-set.generated.d.ts
  src/lib/media-import/status.generated.d.ts
  src/lib/site-import/status.generated.d.ts
  src/lib/validations/is-multi-site.generated.d.ts
  src/lib/validations/is-multisite-domain-mapped.generated.d.ts
  tsconfig.json
Labels: [Status] Ready to Merge

#1428 refactor: convert `validations` to TS
  __tests__/bin/vip-import-sql.js
  src/lib/validations/is-multi-site-sql-dump.ts
  src/lib/validations/is-multi-site.ts
  src/lib/validations/is-multisite-domain-mapped.ts
  src/lib/validations/line-by-line.ts
  src/lib/validations/site-type.ts
  src/lib/validations/sql.ts
  src/lib/validations/utils.ts
Labels: [Status] Needs Review

#1421 refactor: Convert dev-environment to TypeScript
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-start.js
  src/lib/cli/progress.ts
  src/lib/constants/dev-environment.ts
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-configuration-file.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-lando.ts
  src/lib/dev-environment/docker-utils.ts
  src/lib/dev-environment/types.ts
  types/enquirer/index.d.ts
  types/lando/lib/app.d.ts
  types/lando/lib/art.d.ts
  types/lando/lib/bootstrap.d.ts
  types/lando/lib/cache.d.ts
  types/lando/lib/cli.d.ts
  types/lando/lib/compose.d.ts
  types/lando/lib/config.d.ts
  types/lando/lib/daemon.d.ts
  types/lando/lib/docker.d.ts
  types/lando/lib/engine.d.ts
  types/lando/lib/env.d.ts
  types/lando/lib/error.d.ts
  types/lando/lib/events.d.ts
  types/lando/lib/factory.d.ts
  types/lando/lib/formatters.d.ts
  types/lando/lib/lando.d.ts
  types/lando/lib/logger.d.ts
  types/lando/lib/metrics.d.ts
  types/lando/lib/plugins.d.ts
  types/lando/lib/promise.d.ts
  types/lando/lib/router.d.ts
  types/lando/lib/scan.d.ts
  types/lando/lib/shell.d.ts
  types/lando/lib/table.d.ts
  types/lando/lib/user.d.ts
  types/lando/lib/utils.d.ts
  types/lando/lib/yaml.d.ts
  types/lando/plugins/lando-core/lib/utils.d.ts
  types/lando/plugins/lando-tooling/lib/build.d.ts
Labels: [Status] Needs Review

#1448 chore(dev-deps): update babel packages to 7.22.9
  babel.config.js
  npm-shrinkwrap.json
  package.json
Labels: Upstream Dependency

#1341 feat(dev-env): Add a concept of init-only containers
  __tests__/devenv-e2e/003-start.spec.js
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-shell.js
  src/lib/dev-environment/dev-environment-lando.ts
  types/lando/lib/app.d.ts
  types/lando/lib/lando.d.ts
Labels: [Status] Needs Review

#1455 BB8-10502: Fix SQL import command
  npm-shrinkwrap.json
  package.json
  src/lib/client-file-uploader.ts
Labels: [Status] Needs Review

#1456 BB8-10453: Fix DB engine validation regex
  src/lib/validations/sql.ts
Labels: [Status] Needs Review

#1459 Update/npm publish updates
  .github/workflows/prepare-release.yml
  .github/workflows/publish.yml
Labels: [Type] Enhancement

#1470 Rename prepare-release.yml to npm-prepare-release.yml
  .github/workflows/npm-prepare-release.yml
Labels: [Type] Enhancement
