Repository Automattic/vip-cli, pull requests merged in 2023-04, with the labels that each got.

#1326 tests(e2e): Force Jest to exit after all tests have completed running
  __tests__/devenv-e2e/jest/jest.config.js
Labels: [Type] Bug

#1328 feat(dev-env): Profile Lando-related functions
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Status] Needs Review

#1333 [dev-env] Readds xdebug_config to vip dev-env update
  src/lib/dev-environment/dev-environment-configuration-file.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1325 tests: Fix timing out tests on Windows
  .github/workflows/tests.yml
  __tests__/lib/dev-environment/dev-environment-core.js
Labels: [Status] Needs Review

#1337 chore(dev-deps): Update flow-bin from 0.203.1 to 0.204.0
  __tests__/bin/vip-config-envvar-delete.js
  __tests__/bin/vip-config-envvar-set.js
  flow-typed/npm/@apollo/client_v3.x.x.js
  flow-typed/npm/chalk_v4.x.x.js
  flow-typed/npm/jest_v29.x.x.js
  flow-typed/npm/node-fetch_v2.x.x.js
  flow-typed/npm/semver_v7.x.x.js
  npm-shrinkwrap.json
  package.json
Labels: [Status] Needs Review

#1338 chore(dev-deps): Update @automattic/eslint-plugin-wpvip from 0.4.0 to 0.5.2
  .eslintrc.json
  __tests__/bin/vip-config-envvar-delete.js
  __tests__/bin/vip-config-envvar-set.js
  __tests__/commands/dev-env-sync-sql.js
  __tests__/devenv-e2e/helpers/cli-test.js
  __tests__/devenv-e2e/helpers/docker-utils.js
  __tests__/devenv-e2e/helpers/utils.js
  __tests__/devenv-e2e/jest/jest.config.js
  __tests__/devenv-e2e/jest/sequencer.js
  npm-shrinkwrap.json
  package.json
  src/lib/dev-environment/dev-environment-core.js
  src/lib/keychain.js
  src/lib/keychain/browser.js
  src/lib/site-import/status.js
  src/lib/validations/sql.js
  src/lib/vip-import-validate-files.js
Labels: [Status] Needs Review

#1332 Update inline search-replace help for import sql command
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1340 feat(dev-env): Kill lando proxy when last env stops
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Enhancement

#1329 feat(dev-env)!: Replace MailHog with Mailpit
  .github/workflows/devenv-e2e.yml
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/011-configuration-file.spec.js
  __tests__/e2e_test.bat
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-shell.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-configuration-file.js
  src/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-lando.js
  src/lib/dev-environment/types.js
Labels: [Status] Needs Review

#1342 fix(dev-env): Do not fail when lando_bridge_network does not exist
  src/lib/dev-environment/dev-environment-lando.js
Labels: [Type] Bug
