Repository Automattic/vip-cli, pull requests merged in 2024-11, with the labels that each got.

#2061 fix(dev-env): verify the container is running before URL scan
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Type] Bug

#2081 fix(dev-env): detection of URLs to replace for multisites
  __tests__/commands/dev-env-sync-sql.ts
  src/commands/dev-env-import-sql.ts
  src/commands/dev-env-sync-sql.ts
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Type] Bug

#2096 fix: `table` format output
  __tests__/bin/vip-logs.js
  src/bin/vip-logs.js
Labels: [Type] Bug

#2079 Update the `search-replace` command to follow the VIP-CLI style guide
  src/bin/vip-import-sql.js
  src/bin/vip-search-replace.js
  src/bin/vip.js
Labels: [Type] Documentation

#2084 Provide dedicated error message for when a token is marked as disabled due to inactivity
  src/lib/api.ts
Labels: [Status] Needs Review

#2124 Set the mount path for vip-config to ABSPATH/vip-config to match production
  assets/dev-env.lando.template.yml.ejs
  src/lib/constants/dev-environment.ts
Labels: [Status] Needs Review

#2118 Update the`vip validate` command group to follow the VIP-CLI style guide
  src/bin/vip-validate-preflight.js
  src/bin/vip-validate.js
  src/bin/vip.js
Labels: [Type] Documentation
