Repository Automattic/vip-cli, pull requests merged in 2024-04, with the labels that each got.

#1722 Make "importSQLCheckStatus" return immediately when called from the `vip import sql status` command and no import is running
  src/bin/vip-import-sql-status.js
  src/lib/site-import/status.ts
Labels: [Status] Needs Review

#1738 fix(dev-env): regression: stop proxy when there are no running envs
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Type] Bug

#1779 fix(dev-env): argument parsing for `vip dev-env sync sql`
  src/bin/vip-dev-env-sync-sql.js
Labels: [Type] Bug

#1778 fix: underscore is allowed in environment name
  __tests__/lib/cli/envAlias.js
  src/lib/cli/envAlias.ts
Labels: [Type] Bug

#1774 fix: superfluous trailing arguments
  src/bin/vip-dev-env-shell.js
Labels: [Type] Bug

#1746 Update/docs pt vip config
  __tests__/bin/vip-config-envvar-delete.js
  __tests__/bin/vip-config-envvar-get-all.js
  __tests__/bin/vip-config-envvar-get.js
  __tests__/bin/vip-config-envvar-list.js
  __tests__/bin/vip-config-envvar-set.js
  src/bin/vip-config-envvar-delete.js
  src/bin/vip-config-envvar-get-all.js
  src/bin/vip-config-envvar-get.js
  src/bin/vip-config-envvar-list.js
  src/bin/vip-config-envvar-set.js
  src/bin/vip-config-envvar.js
  src/bin/vip-config-software-get.js
  src/bin/vip-config-software-update.js
  src/bin/vip-config-software.js
  src/bin/vip-config.js
  src/bin/vip.js
Labels: [Type] Documentation

#1765 Updates to descriptions and examples for vip db
  src/bin/vip-db-phpmyadmin.ts
  src/bin/vip-db.ts
  src/bin/vip.js
Labels: [Type] Documentation

#1766 Updates to descriptions and examples for vip backup
  src/bin/vip-backup-db.ts
  src/bin/vip-backup.ts
  src/bin/vip.js
Labels: [Type] Documentation

#1794 build: fix `Cannot read properties of undefined` in `generate-docs.js`
  helpers/generate-docs.js
Labels: [Type] Bug

#1783 Update the whoami command to follow the VIP-CLI style guide
  src/bin/vip-whoami.ts
  src/bin/vip.js
Labels: [Type] Documentation
