Repository Automattic/vip-cli, pull requests merged in 2024-10, with the labels that each got.

#2045 docs: update changelog
  docs/CHANGELOG.md
Labels: [Status] Needs Review

#2051 Update the sync command to follow the VIP-CLI style guide
  src/bin/vip-sync.js
  src/bin/vip.js
Labels: [Type] Documentation

#2054 Update the `import` command group to follow the VIP-CLI style guide
  __tests__/bin/vip-import-validate-files.js
  src/bin/vip-import-media-abort.js
  src/bin/vip-import-media-status.js
  src/bin/vip-import-media.js
  src/bin/vip-import-sql-status.js
  src/bin/vip-import-sql.js
  src/bin/vip-import-validate-files.js
  src/bin/vip-import-validate-sql.js
  src/bin/vip-import.js
  src/bin/vip.js
  src/lib/cli/command.js
Labels: [Type] Documentation

#2058 Remove the unused `--format` option from validate media files command
  src/bin/vip-import-validate-files.js
Labels: [Status] Needs Review, [Status] Needs Docs
