Repository Automattic/vip-cli, pull requests merged in 2024-08, with the labels that each got.

#1986 Remove querying `fileErrors` in Graphql API while fetching Media import status
  src/graphqlTypes.d.ts
  src/lib/media-import/status.ts
Labels: [Status] Needs Review

#1962 Mydumper integration
  __fixtures__/dev-env-e2e/mydumper-detection.expected.sql
  __fixtures__/dev-env-e2e/mydumper-detection.sql
  __fixtures__/dev-env-e2e/mydumper-detection.sql.gz
  __fixtures__/dev-env-e2e/mysqldump-detection.sql
  __fixtures__/dev-env-e2e/mysqldump-detection.sql.gz
  __tests__/commands/dev-env-sync-sql.ts
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-import-sql.js
  src/commands/dev-env-import-sql.ts
  src/commands/dev-env-sync-sql.ts
  src/lib/database.ts
  src/lib/promise.ts
  src/lib/search-and-replace.ts
  src/lib/types.ts
  src/lib/validations/sql.ts
Labels: [Status] Needs Review

#1992 fix(dev-env): clean up data after `vip dev-env sync sql`
  src/commands/dev-env-import-sql.ts
  src/lib/dev-environment/dev-environment-database.ts
Labels: [Type] Bug

#1996 docs: update changelog
  docs/CHANGELOG.md
Labels: [Status] Needs Review

#1965 chore(deps): make `node-fetch` 2.x depend on `whatwg-url` 14.x to address deprecations
  npm-shrinkwrap.json
  package.json
Labels: [Type] Bug, dependencies

#2012 fix(import-media): Display success/total count even if all files fail to import
  src/lib/media-import/progress.ts
  src/lib/media-import/status.ts
Labels: [Status] Needs Review
