Repository Automattic/vip-cli, pull requests merged in 2024-05, with the labels that each got.

#1815 fix(dev-env): `vip dev-env info --all` should not ask for a slug
  src/bin/vip-dev-env-info.js
Labels: [Type] Bug, [Status] Needs Review

#1830 Add new lines after error file URLs
  src/lib/media-import/status.ts
Labels: [Status] Needs Review

#1837 feat(dev-env): track versions of `docker` and `docker-compose`
  src/bin/vip-dev-env-start.js
Labels: [Type] Enhancement

#1846 ci: add publish prerelease workflow
  .github/workflows/npm-publish-prerelease.yml
Labels: [Type] Enhancement

#1838 Update the dev-env commands to follow the VIP-CLI style guide
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-import.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-list.js
  src/bin/vip-dev-env-logs.js
  src/bin/vip-dev-env-purge.js
  src/bin/vip-dev-env-shell.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-sync-sql.js
  src/bin/vip-dev-env-sync.js
  src/bin/vip-dev-env-update.js
  src/bin/vip-dev-env.js
  src/bin/vip.js
Labels: [Type] Documentation
