Repository Automattic/vip-cli, pull requests merged in 2024-06, with the labels that each got.

#1852 fix(dev-env): demo code is displayed as `[demo-image]`
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug

#1859 feat(dev-env): make `domain` configurable
  __tests__/lib/dev-environment/dev-environment-core.js
  assets/dev-env.lando.template.yml.ejs
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Status] Needs Docs

#1854 feat(dev-env): add `--all` to `vip dev-env stop`
  __tests__/devenv-e2e/004-stop.spec.js
  src/bin/vip-dev-env-stop.js
Labels: [Type] Enhancement, [Status] Needs Docs

#1845 chore: update lando to 77dad3a
  __tests__/lib/dev-environment/dev-environment-core.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-start.js
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-lando.ts
Labels: dependencies, [Status] Needs Docs

#1851 fix: CVE-2024-29415 in `socks`
  npm-shrinkwrap.json
Labels: dependencies

#1862 fix(dev-env): allow for unsetting media redirect domain
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Type] Bug, [Status] Needs Docs

#1863 fix(dev-env): validate version values
  .github/workflows/devenv-e2e.yml
  __fixtures__/dev-env-e2e/.lando_mariadb.yml
  __fixtures__/dev-env-e2e/instance_data_mariadb.json
  __tests__/e2e_test.bat
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/lib/constants/dev-environment.ts
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-configuration-file.ts
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug, [Status] Needs Docs

#1868 fix(dev-env): make sure wildcard subdomains work with SSL/TLS
  assets/dev-env.lando.template.yml.ejs
Labels: [Type] Bug

#1867 feat(dev-env): add XDebug information to `vip dev-env info --extended`
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Enhancement

#1866 Updating command option descriptions to follow the VIP-CLI style guide
  src/bin/vip-config-software-update.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-sync.js
  src/lib/cli/command.js
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Type] Documentation

#1888 fix(dev-env): force pull images on environment version update
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug, [Status] Needs Review

#1895 fix(dev-env): set the user/group for `nginx` container to `nginx:nginx`
  assets/dev-env.lando.template.yml.ejs
Labels: [Status] Needs Review

#1907 fix(dev-env): ensure that URLs suggested for replacement start with `http(s)://`
  __fixtures__/validations/bad-sql-dev-env.sql
  __tests__/lib/validations/sql.js
  src/lib/validations/sql.ts
Labels: [Type] Bug

#1908 Update the vip app command to follow the VIP-CLI style guide
  src/bin/vip-app-deploy-validate.ts
  src/bin/vip-app-deploy.ts
  src/bin/vip-app-list.js
  src/bin/vip-app.js
  src/bin/vip.js
  src/lib/validations/custom-deploy.ts
Labels: [Type] Documentation

#1909 Add retries to the fetching of jobs data
  __tests__/commands/export-sql.js
  src/commands/export-sql.js
  src/lib/retry.ts
Labels: [Status] Needs Review

#1892 feat(dev-env): add support for cron
  __tests__/devenv-e2e/001-create.spec.js
  __tests__/devenv-e2e/005-update.spec.js
  __tests__/devenv-e2e/013-configuration-file.spec.js
  __tests__/lib/dev-environment/dev-environment-cli.js
  assets/dev-env.lando.template.yml.ejs
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-configuration-file.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/types.ts
Labels: [Type] Enhancement, [Status] Needs Docs
