Repository Automattic/vip-cli, pull requests merged in 2024-03, with the labels that each got.

#1716 Fix triggering publish docs workflow on tag push
  .github/workflows/publish-docs.yml
Labels: [Type] Bug

#1632 Allows user to continue even when the answer doesn't match the expected letter casing
  __tests__/bin/vip-import-sql.js
  src/bin/vip-app-deploy.ts
  src/bin/vip-import-sql.js
Labels: [Status] Ready to Merge

#1743 Update SQL import prompt message
  src/bin/vip-import-sql.js
Labels: [Status] Needs Review

#1741 Updated the export command group according to VIP-CLI style guide
  src/bin/vip-export-sql.js
  src/bin/vip-export.js
  src/bin/vip.js
Labels: [Type] Documentation
