Repository Automattic/vip-cli, pull requests merged in 2024-01, with the labels that each got.

#1630 fix(validate-sql): Display matched site-urls
  src/lib/validations/sql.ts
Labels: [Status] Needs Review

#1643 chore(deps): fix CVE-2023-26159 in follow-redirects
  npm-shrinkwrap.json
Labels: [Status] Needs Review, dependencies

#1626 fix: Properly propagate quotes
  __tests__/lib/cli/format.js
  src/lib/cli/format.ts
Labels: [Status] Needs Review

#1631 fix(--format=json): Do not print header if specified format is json
  src/lib/cli/command.js
Labels: [Status] Ready to Merge

#1615 feat(dev-env): add quiet mode for "import sql"
  __tests__/commands/dev-env-sync-sql.js
  src/bin/vip-dev-env-import-sql.js
  src/commands/dev-env-import-sql.js
  src/commands/dev-env-sync-sql.js
Labels: [Status] Needs Docs

#1639 fix: regex vulnerable to super-linear runtime
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/docker-utils.ts
Labels: [Type] Bug

#1650 fix(dev-env): CWE-367 in `prepareLandoEnv()`
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug, [Status] Needs Review

#1652 fix(dev-env): CWE-367 in `getConfigurationFileOptions()`
  src/lib/dev-environment/dev-environment-configuration-file.ts
Labels: [Type] Bug

#1654 fix(dev-env): CWE-377, CWE-378 originating from `xdgDataDirectory()`
  __tests__/lib/dev-environment/dev-environment-core.js
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug

#1659 fix(dev-env): always lowercase environment slug
  src/bin/vip-dev-env-create.js
  src/bin/vip-dev-env-destroy.js
  src/bin/vip-dev-env-exec.js
  src/bin/vip-dev-env-import-media.js
  src/bin/vip-dev-env-import-sql.js
  src/bin/vip-dev-env-info.js
  src/bin/vip-dev-env-logs.js
  src/bin/vip-dev-env-shell.js
  src/bin/vip-dev-env-start.js
  src/bin/vip-dev-env-stop.js
  src/bin/vip-dev-env-sync-sql.js
  src/bin/vip-dev-env-update.js
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Type] Bug

#1468 Use vip dev-env configuration file from parent directories
  __tests__/devenv-e2e/013-configuration-file.spec.js
  __tests__/devenv-e2e/helpers/utils.js
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/bin/vip-dev-env-create.js
  src/bin/vip-wp.js
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-configuration-file.ts
  src/lib/dev-environment/types.ts
Labels: [Status] Needs Docs

#1665 Add step to enable PHPMyAdmin in the phpmyadmin command
  __tests__/commands/phpmyadmin.ts
  src/commands/phpmyadmin.ts
Labels: [Status] Needs Review, [Status] Needs Tests

#1672 Track errors encounted at get-status
  src/commands/phpmyadmin.ts
Labels: [Status] Needs Review
