Repository Automattic/vip-cli, pull requests merged in 2024-07, with the labels that each got.

#1914 fix(dev-env): display all port mappings
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Type] Bug, [Status] Needs Docs

#1918 fix(dev-env): display cron status in `vip dev-env info --extended`
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug

#1924 fix: case mismatch in environment identifier matcher
  src/lib/cli/command.js
Labels: [Type] Bug

#1955 Refactor `dev-env sync`, `dev-env import` and `export-sql` to TypeScript
  __tests__/commands/dev-env-sync-sql.ts
  __tests__/commands/export-sql.ts
  src/commands/dev-env-import-sql.ts
  src/commands/dev-env-sync-sql.ts
  src/commands/export-sql.ts
  src/lib/analytics/clients/tracks.ts
  src/lib/cli/format.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-lando.ts
Labels: [Status] Needs Review
