Repository Automattic/vip-cli, pull requests merged in 2025-06, with the labels that each got.

#2397 docs: update changelog
  docs/CHANGELOG.md
Labels: [Status] Needs Review

#2184 fix: properly quote parameters for `vip wp`
  __tests__/lib/cli/format.js
  src/lib/cli/format.ts
Labels: [Type] Bug

#2415 fix(dev-env): clear proxy cache before startup and after shutdown
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-lando.ts
  types/lando/lib/lando.d.ts
Labels: [Type] Bug

#2398 feat(dev-env): add `vip dev-env envvar` commands
  __tests__/lib/dev-environment/env-vars.spec.js
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-envvar-delete.js
  src/bin/vip-dev-env-envvar-get-all.js
  src/bin/vip-dev-env-envvar-get.js
  src/bin/vip-dev-env-envvar-list.js
  src/bin/vip-dev-env-envvar-set.js
  src/bin/vip-dev-env-envvar.js
  src/bin/vip-dev-env.js
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/env-vars.ts
Labels: [Status] Needs Docs

#2425 fix: suppress prompt for media redirect with config files
  src/lib/dev-environment/dev-environment-cli.ts
Labels: Bug

#2422 Remove preflight as part of the harmonia deprecation
  npm-shrinkwrap.json
  package.json
  src/bin/vip-validate-preflight.generated.d.ts
  src/bin/vip-validate-preflight.js
  src/bin/vip-validate.js
  src/bin/vip.js
Labels: [Status] Needs Docs
