Repository Automattic/vip-cli, pull requests merged in 2025-03, with the labels that each got.

#2256 fix(dev-env): accept `demo` as an alias of `image`
  src/lib/dev-environment/dev-environment-configuration-file.ts
Labels: [Status] Needs Review

#2255 Update/search replace example
  src/bin/vip-search-replace.js
Labels: [Type] Documentation

#2279 feat(dev-env): add initial support for `.env` files
  __tests__/lib/dev-environment/dev-environment-core.js
  assets/dev-env.lando.template.yml.ejs
  npm-shrinkwrap.json
  package.json
  src/bin/vip-dev-env-create.js
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-lando.ts
  src/lib/dev-environment/types.ts
Labels: [Status] Needs Docs

#2218 feat(dev-env): Refactor IDE support: add Cursor, PHPStorm and Windsurf
  src/bin/vip-dev-env-start.js
  src/lib/dev-environment/dev-environment-cli.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/types.ts
Labels: [Status] Needs Docs

#2173 fix(dev-env): disallow running dev-env as `root`
  src/bin/vip-dev-env.js
Labels: [Type] Enhancement, [Status] Needs Docs

#2295 fix(dev-env): handling of large media files in `vip dev-env import media`
  npm-shrinkwrap.json
  package.json
  src/lib/dev-environment/dev-environment-core.ts
Labels: [Type] Bug, [Status] Needs Review

#2294 fix(dev-env): handling of `mediaRedirectDomain` in `vip dev-env update`
  __tests__/lib/dev-environment/dev-environment-cli.js
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Type] Bug
