Repository Automattic/vip-cli, pull requests merged in 2025-07, with the labels that each got.

#2451 Update to the description of the `--wordpress` option for `dev-env`
  src/lib/dev-environment/dev-environment-cli.ts
Labels: [Type] Documentation

#2453 fix: drop superfluous `as unknown` casts
  __tests__/commands/wp-ssh.ts
  src/commands/export-sql.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/media-import/config.ts
  src/lib/media-import/status.ts
Labels: Bug

#2457 fix: exception handling-related code smells
  src/bin/vip-import-media.js
  src/bin/vip-import-sql.js
  src/lib/custom-deploy/custom-deploy.ts
  src/lib/dev-environment/dev-environment-core.ts
  src/lib/dev-environment/dev-environment-database.ts
  src/lib/dev-environment/dev-environment-lando.ts
  src/lib/site-import/status.ts
  src/lib/validations/line-by-line.ts
Labels: Bug

#2456 fix: Promise rejection is not caught by `try`
  src/commands/wp-ssh.ts
Labels: Bug

#2471 security: update `form-data` to fix CVE-2025-7783
  npm-shrinkwrap.json
Labels: dependencies

#2475 fix(wp): EventEmitter memory leak for `error` listeners
  src/bin/vip-wp.js
Labels: Bug
